# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "isoF+sFFeX5rM3yC+Q2j3vIhPeNg1LOqCEMzJwMEeY6C65wROOge1LYiApTHEYyitEGq2F/jzC9ATe2G0zyX5mTBVHiLQN3pCs66EjTFjTzVVtMb0wjGe4bCgUlXOfgRe/Nn62VRFmETYjZ25jtie9dkAiIV3hiLMMdrNHei/dUCKeT78Q6FkyRjfqPbQCE0eXJlvBoCWBvptY2iN+3s16fVQfE92eW5onVj9agttaZlO83dk3M9ioxolJb0/9PfnT7Jua17+qGWsMN7+H9uIJ5/rfu+5me+75iDttIZRBigP8cyutr3f0en33If+EM3aFJREFE1KbB4ACmIWRAr6j5Bndl65gBRdNLQdzOIQKS7pRwzsaolFtpKRKZ3syTABLvcfD0UpmrSxehvPXpkbhI5tca15mek2AaTZK3zxy0nKLSqAcVHhB8okij+sQRPQHHB8P+KbEY0eLRjZ7R4C0rDn9Rmlq7mVE40+tQoNe6LXzcWBGcyFGALZ647ThJsTJuQv2AG2HQ2jzWz0JgGrlGjs9aDDjwgUpSh7Mws3okl9oQ1BRF1JSuoLChDOwcqKocQvJXpvVAg6Rcgkg3plT3GSbrIjPBmQDm2luOd8YgOS09+ThAd+K7p6Pg2HMU5x6btn4PdsN0/lPOokCv/FMrEKQWuYmQKmx1/UYeTEm8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
