travis:
  secure:
    BINSTAR_TOKEN: isoF+sFFeX5rM3yC+Q2j3vIhPeNg1LOqCEMzJwMEeY6C65wROOge1LYiApTHEYyitEGq2F/jzC9ATe2G0zyX5mTBVHiLQN3pCs66EjTFjTzVVtMb0wjGe4bCgUlXOfgRe/Nn62VRFmETYjZ25jtie9dkAiIV3hiLMMdrNHei/dUCKeT78Q6FkyRjfqPbQCE0eXJlvBoCWBvptY2iN+3s16fVQfE92eW5onVj9agttaZlO83dk3M9ioxolJb0/9PfnT7Jua17+qGWsMN7+H9uIJ5/rfu+5me+75iDttIZRBigP8cyutr3f0en33If+EM3aFJREFE1KbB4ACmIWRAr6j5Bndl65gBRdNLQdzOIQKS7pRwzsaolFtpKRKZ3syTABLvcfD0UpmrSxehvPXpkbhI5tca15mek2AaTZK3zxy0nKLSqAcVHhB8okij+sQRPQHHB8P+KbEY0eLRjZ7R4C0rDn9Rmlq7mVE40+tQoNe6LXzcWBGcyFGALZ647ThJsTJuQv2AG2HQ2jzWz0JgGrlGjs9aDDjwgUpSh7Mws3okl9oQ1BRF1JSuoLChDOwcqKocQvJXpvVAg6Rcgkg3plT3GSbrIjPBmQDm2luOd8YgOS09+ThAd+K7p6Pg2HMU5x6btn4PdsN0/lPOokCv/FMrEKQWuYmQKmx1/UYeTEm8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
